#!/bin/bash

T=/dev/tty0

if [[ "$1" = "cl" ]]; then
    setterm --reset >$T
    setterm --cursor off >$T
    setterm --blank 0 >$T
    setterm --clear all >$T
fi

if [[ "$1" = "fl" ]]; then
    $0 cl
    setterm --background red >$T
    setterm --clear all >$T
    sleep 0.5
    $0 cl
fi

if [[ "$1" = "s" ]]; then
    $0 cl
    setterm --background black >$T
    setterm --foreground yellow >$T
    cat >$T <<EOF




EOF
    setterm --clear all >$T
    /usr/games/cowsay -f dragon "$2" >$T
    sleep 2.5
    $0 cl
fi
